/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Sat Jan 03 21:16:32 2026 */

/* parameterized module instance */
pll_64_new __ (.CLKI( ), .RST( ), .CLKOP( ), .LOCK( ));
