/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 1.6 */
/* Fri Jan 09 17:18:08 2026 */

/* parameterized module instance */
SinCos_Module __ (.Clock( ), .ClkEn( ), .Reset( ), .Theta( ), .Sine( ), 
    .Cosine( ));
