/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 4.9 */
/* C:\lscc\diamond\3.14\ispfpga\bin\nt64\scuba.exe -w -n multiplier_12_2_m -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00g -type dspmult -simple_portname -pfu_mult -widtha 2 -widthb 12 -widthp 14 -signed -PL_stages 1 -input_reg -output_reg -clk0 -ce0 -rst0 -fdc C:/Users/SNA/Documents/FPGA_code/lattice_sdr_code/multiplier/multiplier_12_2_m/multiplier_12_2_m.fdc  */
/* Fri Jan 09 17:03:38 2026 */


`timescale 1 ns / 1 ps
module multiplier_12_2_m (Clock, ClkEn, Aclr, DataA, DataB, Result)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClkEn;
    input wire Aclr;
    input wire [1:0] DataA;
    input wire [11:0] DataB;
    output wire [13:0] Result;

    wire multiplier_12_2_m_0_pp_0_0;
    wire regb_b_0;
    wire rego_o_0;
    wire p_L1_0;
    wire rego_o_1;
    wire p_L1_1;
    wire rego_o_2;
    wire p_L1_2;
    wire rego_o_3;
    wire p_L1_3;
    wire rego_o_4;
    wire p_L1_4;
    wire rego_o_5;
    wire p_L1_5;
    wire rego_o_6;
    wire p_L1_6;
    wire rego_o_7;
    wire p_L1_7;
    wire rego_o_8;
    wire p_L1_8;
    wire rego_o_9;
    wire p_L1_9;
    wire rego_o_10;
    wire p_L1_10;
    wire rego_o_11;
    wire p_L1_11;
    wire rego_o_12;
    wire p_L1_12;
    wire rego_o_13;
    wire p_L1_13;
    wire multiplier_12_2_m_0_pp_0_13;
    wire scuba_vlo;
    wire multiplier_12_2_m_0_pp_0_2;
    wire multiplier_12_2_m_0_pp_0_1;
    wire multiplier_12_2_m_0_cin_lr;
    wire regb_b_2;
    wire multiplier_12_2_m_0_mult_0_0_n1;
    wire regb_b_1;
    wire multiplier_12_2_m_0_mult_0_0_n0;
    wire multiplier_12_2_m_0_pp_0_4;
    wire multiplier_12_2_m_0_pp_0_3;
    wire mco;
    wire regb_b_4;
    wire multiplier_12_2_m_0_mult_0_1_n1;
    wire regb_b_3;
    wire multiplier_12_2_m_0_mult_0_1_n0;
    wire multiplier_12_2_m_0_pp_0_6;
    wire multiplier_12_2_m_0_pp_0_5;
    wire mco_1;
    wire regb_b_6;
    wire multiplier_12_2_m_0_mult_0_2_n1;
    wire regb_b_5;
    wire multiplier_12_2_m_0_mult_0_2_n0;
    wire multiplier_12_2_m_0_pp_0_8;
    wire multiplier_12_2_m_0_pp_0_7;
    wire mco_2;
    wire regb_b_8;
    wire multiplier_12_2_m_0_mult_0_3_n1;
    wire regb_b_7;
    wire multiplier_12_2_m_0_mult_0_3_n0;
    wire multiplier_12_2_m_0_pp_0_10;
    wire multiplier_12_2_m_0_pp_0_9;
    wire mco_3;
    wire regb_b_10;
    wire multiplier_12_2_m_0_mult_0_4_n1;
    wire regb_b_9;
    wire multiplier_12_2_m_0_mult_0_4_n0;
    wire mfco;
    wire multiplier_12_2_m_0_pp_0_12;
    wire multiplier_12_2_m_0_pp_0_11;
    wire mco_4;
    wire rega_a_1;
    wire rega_a_0;
    wire scuba_vhi;
    wire multiplier_12_2_m_0_mult_0_5_n3;
    wire regb_b_11;
    wire multiplier_12_2_m_0_mult_0_5_n0;

    AND2 AND2_t12 (.A(regb_b_0), .B(rega_a_0), .Z(multiplier_12_2_m_0_pp_0_0));

    ND2 ND2_t11 (.A(regb_b_1), .B(rega_a_1), .Z(multiplier_12_2_m_0_mult_0_0_n1));

    ND2 ND2_t10 (.A(regb_b_0), .B(rega_a_1), .Z(multiplier_12_2_m_0_mult_0_0_n0));

    ND2 ND2_t9 (.A(regb_b_3), .B(rega_a_1), .Z(multiplier_12_2_m_0_mult_0_1_n1));

    ND2 ND2_t8 (.A(regb_b_2), .B(rega_a_1), .Z(multiplier_12_2_m_0_mult_0_1_n0));

    ND2 ND2_t7 (.A(regb_b_5), .B(rega_a_1), .Z(multiplier_12_2_m_0_mult_0_2_n1));

    ND2 ND2_t6 (.A(regb_b_4), .B(rega_a_1), .Z(multiplier_12_2_m_0_mult_0_2_n0));

    ND2 ND2_t5 (.A(regb_b_7), .B(rega_a_1), .Z(multiplier_12_2_m_0_mult_0_3_n1));

    ND2 ND2_t4 (.A(regb_b_6), .B(rega_a_1), .Z(multiplier_12_2_m_0_mult_0_3_n0));

    ND2 ND2_t3 (.A(regb_b_9), .B(rega_a_1), .Z(multiplier_12_2_m_0_mult_0_4_n1));

    ND2 ND2_t2 (.A(regb_b_8), .B(rega_a_1), .Z(multiplier_12_2_m_0_mult_0_4_n0));

    ND2 ND2_t1 (.A(regb_b_11), .B(rega_a_0), .Z(multiplier_12_2_m_0_mult_0_5_n3));

    ND2 ND2_t0 (.A(regb_b_10), .B(rega_a_1), .Z(multiplier_12_2_m_0_mult_0_5_n0));

    FD1P3DX FF_41 (.D(DataA[0]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_40 (.D(DataA[1]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_39 (.D(DataB[0]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_38 (.D(DataB[1]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_37 (.D(DataB[2]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_36 (.D(DataB[3]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_35 (.D(DataB[4]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_34 (.D(DataB[5]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_33 (.D(DataB[6]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_32 (.D(DataB[7]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_31 (.D(DataB[8]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_30 (.D(DataB[9]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_29 (.D(DataB[10]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(DataB[11]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(rego_o_0), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(rego_o_1), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(rego_o_2), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(rego_o_3), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(rego_o_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(rego_o_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(rego_o_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(rego_o_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(rego_o_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(rego_o_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[9]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(rego_o_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[10]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(rego_o_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[11]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(rego_o_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[12]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(rego_o_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[13]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(p_L1_0), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(p_L1_1), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(p_L1_2), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(p_L1_3), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(p_L1_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(p_L1_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(p_L1_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(p_L1_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(p_L1_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(p_L1_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(p_L1_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(p_L1_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(p_L1_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(p_L1_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rego_o_13))
             /* synthesis GSR="ENABLED" */;

    defparam multiplier_12_2_m_0_cin_lr_add.INJECT1_1 = "NO" ;
    defparam multiplier_12_2_m_0_cin_lr_add.INJECT1_0 = "NO" ;
    defparam multiplier_12_2_m_0_cin_lr_add.INIT1 =  16'h66AA ;
    defparam multiplier_12_2_m_0_cin_lr_add.INIT0 =  16'h66AA ;
    CCU2C multiplier_12_2_m_0_cin_lr_add (.A0(scuba_vhi), .A1(scuba_vhi), 
        .B0(scuba_vhi), .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(multiplier_12_2_m_0_cin_lr));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam multiplier_12_2_m_0_Cadd_0_6.INJECT1_1 = "NO" ;
    defparam multiplier_12_2_m_0_Cadd_0_6.INJECT1_0 = "NO" ;
    defparam multiplier_12_2_m_0_Cadd_0_6.INIT1 =  16'h66AA ;
    defparam multiplier_12_2_m_0_Cadd_0_6.INIT0 =  16'h66AA ;
    CCU2C multiplier_12_2_m_0_Cadd_0_6 (.A0(scuba_vhi), .A1(scuba_vlo), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(mfco), .S0(multiplier_12_2_m_0_pp_0_13), 
        .S1(), .COUT());

    defparam multiplier_12_2_m_0_mult_0_0.INJECT1_1 = "NO" ;
    defparam multiplier_12_2_m_0_mult_0_0.INJECT1_0 = "NO" ;
    defparam multiplier_12_2_m_0_mult_0_0.INIT1 =  16'h7888 ;
    defparam multiplier_12_2_m_0_mult_0_0.INIT0 =  16'h7888 ;
    CCU2C multiplier_12_2_m_0_mult_0_0 (.A0(multiplier_12_2_m_0_mult_0_0_n0), 
        .A1(multiplier_12_2_m_0_mult_0_0_n1), .B0(scuba_vhi), .B1(scuba_vhi), 
        .C0(regb_b_1), .C1(regb_b_2), .D0(rega_a_0), .D1(rega_a_0), .CIN(multiplier_12_2_m_0_cin_lr), 
        .S0(multiplier_12_2_m_0_pp_0_1), .S1(multiplier_12_2_m_0_pp_0_2), 
        .COUT(mco));

    defparam multiplier_12_2_m_0_mult_0_1.INJECT1_1 = "NO" ;
    defparam multiplier_12_2_m_0_mult_0_1.INJECT1_0 = "NO" ;
    defparam multiplier_12_2_m_0_mult_0_1.INIT1 =  16'h7888 ;
    defparam multiplier_12_2_m_0_mult_0_1.INIT0 =  16'h7888 ;
    CCU2C multiplier_12_2_m_0_mult_0_1 (.A0(multiplier_12_2_m_0_mult_0_1_n0), 
        .A1(multiplier_12_2_m_0_mult_0_1_n1), .B0(scuba_vhi), .B1(scuba_vhi), 
        .C0(regb_b_3), .C1(regb_b_4), .D0(rega_a_0), .D1(rega_a_0), .CIN(mco), 
        .S0(multiplier_12_2_m_0_pp_0_3), .S1(multiplier_12_2_m_0_pp_0_4), 
        .COUT(mco_1));

    defparam multiplier_12_2_m_0_mult_0_2.INJECT1_1 = "NO" ;
    defparam multiplier_12_2_m_0_mult_0_2.INJECT1_0 = "NO" ;
    defparam multiplier_12_2_m_0_mult_0_2.INIT1 =  16'h7888 ;
    defparam multiplier_12_2_m_0_mult_0_2.INIT0 =  16'h7888 ;
    CCU2C multiplier_12_2_m_0_mult_0_2 (.A0(multiplier_12_2_m_0_mult_0_2_n0), 
        .A1(multiplier_12_2_m_0_mult_0_2_n1), .B0(scuba_vhi), .B1(scuba_vhi), 
        .C0(regb_b_5), .C1(regb_b_6), .D0(rega_a_0), .D1(rega_a_0), .CIN(mco_1), 
        .S0(multiplier_12_2_m_0_pp_0_5), .S1(multiplier_12_2_m_0_pp_0_6), 
        .COUT(mco_2));

    defparam multiplier_12_2_m_0_mult_0_3.INJECT1_1 = "NO" ;
    defparam multiplier_12_2_m_0_mult_0_3.INJECT1_0 = "NO" ;
    defparam multiplier_12_2_m_0_mult_0_3.INIT1 =  16'h7888 ;
    defparam multiplier_12_2_m_0_mult_0_3.INIT0 =  16'h7888 ;
    CCU2C multiplier_12_2_m_0_mult_0_3 (.A0(multiplier_12_2_m_0_mult_0_3_n0), 
        .A1(multiplier_12_2_m_0_mult_0_3_n1), .B0(scuba_vhi), .B1(scuba_vhi), 
        .C0(regb_b_7), .C1(regb_b_8), .D0(rega_a_0), .D1(rega_a_0), .CIN(mco_2), 
        .S0(multiplier_12_2_m_0_pp_0_7), .S1(multiplier_12_2_m_0_pp_0_8), 
        .COUT(mco_3));

    defparam multiplier_12_2_m_0_mult_0_4.INJECT1_1 = "NO" ;
    defparam multiplier_12_2_m_0_mult_0_4.INJECT1_0 = "NO" ;
    defparam multiplier_12_2_m_0_mult_0_4.INIT1 =  16'h7888 ;
    defparam multiplier_12_2_m_0_mult_0_4.INIT0 =  16'h7888 ;
    CCU2C multiplier_12_2_m_0_mult_0_4 (.A0(multiplier_12_2_m_0_mult_0_4_n0), 
        .A1(multiplier_12_2_m_0_mult_0_4_n1), .B0(scuba_vhi), .B1(scuba_vhi), 
        .C0(regb_b_9), .C1(regb_b_10), .D0(rega_a_0), .D1(rega_a_0), .CIN(mco_3), 
        .S0(multiplier_12_2_m_0_pp_0_9), .S1(multiplier_12_2_m_0_pp_0_10), 
        .COUT(mco_4));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    defparam multiplier_12_2_m_0_mult_0_5.INJECT1_1 = "NO" ;
    defparam multiplier_12_2_m_0_mult_0_5.INJECT1_0 = "NO" ;
    defparam multiplier_12_2_m_0_mult_0_5.INIT1 =  16'h7888 ;
    defparam multiplier_12_2_m_0_mult_0_5.INIT0 =  16'h7888 ;
    CCU2C multiplier_12_2_m_0_mult_0_5 (.A0(multiplier_12_2_m_0_mult_0_5_n0), 
        .A1(regb_b_11), .B0(scuba_vhi), .B1(rega_a_1), .C0(regb_b_11), .C1(multiplier_12_2_m_0_mult_0_5_n3), 
        .D0(rega_a_0), .D1(scuba_vhi), .CIN(mco_4), .S0(multiplier_12_2_m_0_pp_0_11), 
        .S1(multiplier_12_2_m_0_pp_0_12), .COUT(mfco));

    assign p_L1_0 = multiplier_12_2_m_0_pp_0_0;
    assign p_L1_1 = multiplier_12_2_m_0_pp_0_1;
    assign p_L1_2 = multiplier_12_2_m_0_pp_0_2;
    assign p_L1_3 = multiplier_12_2_m_0_pp_0_3;
    assign p_L1_4 = multiplier_12_2_m_0_pp_0_4;
    assign p_L1_5 = multiplier_12_2_m_0_pp_0_5;
    assign p_L1_6 = multiplier_12_2_m_0_pp_0_6;
    assign p_L1_7 = multiplier_12_2_m_0_pp_0_7;
    assign p_L1_8 = multiplier_12_2_m_0_pp_0_8;
    assign p_L1_9 = multiplier_12_2_m_0_pp_0_9;
    assign p_L1_10 = multiplier_12_2_m_0_pp_0_10;
    assign p_L1_11 = multiplier_12_2_m_0_pp_0_11;
    assign p_L1_12 = multiplier_12_2_m_0_pp_0_12;
    assign p_L1_13 = multiplier_12_2_m_0_pp_0_13;


    // exemplar begin
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
