/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 4.9 */
/* Fri Jan 09 17:03:38 2026 */

/* parameterized module instance */
multiplier_12_2_m __ (.Clock( ), .ClkEn( ), .Aclr( ), .DataA( ), 
    .DataB( ), .Result( ));
