/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Sat Jan 03 19:27:33 2026 */

/* parameterized module instance */
pll_64 __ (.CLKI( ), .RST( ), .CLKOP( ), .LOCK( ));
