/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 1.6 */
/* C:\lscc\diamond\3.14\ispfpga\bin\nt64\scuba.exe -w -n SinCos_Module -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00g -type cosine -addr_width 10 -width 12 -pfu -input_reg -mode 2 -output_reg -area -pipeline 1 -fdc C:/Users/SNA/Documents/FPGA_code/lattice_sdr_code/creating_nco/SinCos_Module/SinCos_Module.fdc  */
/* Fri Jan 09 17:18:08 2026 */


`timescale 1 ns / 1 ps
module SinCos_Module (Clock, ClkEn, Reset, Theta, Sine, Cosine)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClkEn;
    input wire Reset;
    input wire [9:0] Theta;
    output wire [11:0] Sine;
    output wire [11:0] Cosine;

    wire func_or_inet_1;
    wire func_or_inet;
    wire lx_ne0;
    wire lx_ne0_inv;
    wire mx_ctrl_r_1_inv;
    wire rom_addr0_r;
    wire rom_addr0_r_1;
    wire rom_addr0_r_2;
    wire rom_addr0_r_3;
    wire rom_addr0_r_4;
    wire rom_addr0_r_5;
    wire rom_addr0_r_6;
    wire mx_ctrl_r;
    wire rom_addr0_r_7;
    wire cosromoutsel_i;
    wire rom_dout;
    wire rom_dout_1;
    wire rom_dout_2;
    wire rom_dout_3;
    wire rom_dout_4;
    wire rom_dout_5;
    wire rom_dout_6;
    wire rom_dout_7;
    wire rom_dout_8;
    wire rom_dout_9;
    wire rom_dout_10;
    wire sinromoutsel;
    wire rom_dout_11;
    wire rom_dout_12;
    wire rom_dout_13;
    wire rom_dout_14;
    wire rom_dout_15;
    wire rom_dout_16;
    wire rom_dout_17;
    wire rom_dout_18;
    wire rom_dout_19;
    wire rom_dout_20;
    wire rom_dout_21;
    wire rom_dout_22;
    wire cosromoutsel;
    wire rom_dout_23;
    wire out_sel_i;
    wire rom_dout_s;
    wire rom_dout_s_1;
    wire rom_dout_s_2;
    wire rom_dout_s_3;
    wire rom_dout_s_4;
    wire rom_dout_s_5;
    wire rom_dout_s_6;
    wire rom_dout_s_7;
    wire rom_dout_s_8;
    wire rom_dout_s_9;
    wire rom_dout_s_10;
    wire mx_ctrl_r_1;
    wire rom_dout_s_11;
    wire rom_dout_c;
    wire rom_dout_c_1;
    wire rom_dout_c_2;
    wire rom_dout_c_3;
    wire rom_dout_c_4;
    wire rom_dout_c_5;
    wire rom_dout_c_6;
    wire rom_dout_c_7;
    wire rom_dout_c_8;
    wire rom_dout_c_9;
    wire rom_dout_c_10;
    wire out_sel;
    wire rom_dout_c_11;
    wire sinout_pre;
    wire sinout_pre_1;
    wire sinout_pre_2;
    wire sinout_pre_3;
    wire sinout_pre_4;
    wire sinout_pre_5;
    wire sinout_pre_6;
    wire sinout_pre_7;
    wire sinout_pre_8;
    wire sinout_pre_9;
    wire sinout_pre_10;
    wire sinout_pre_11;
    wire cosout_pre;
    wire cosout_pre_1;
    wire cosout_pre_2;
    wire cosout_pre_3;
    wire cosout_pre_4;
    wire cosout_pre_5;
    wire cosout_pre_6;
    wire cosout_pre_7;
    wire cosout_pre_8;
    wire cosout_pre_9;
    wire cosout_pre_10;
    wire cosout_pre_11;
    wire rom_addr0_r_n;
    wire rom_addr0_r_inv;
    wire rom_addr0_r_n_1;
    wire rom_addr0_r_n_2;
    wire rom_addr0_r_2_inv;
    wire rom_addr0_r_1_inv;
    wire co0;
    wire rom_addr0_r_n_3;
    wire rom_addr0_r_n_4;
    wire rom_addr0_r_4_inv;
    wire rom_addr0_r_3_inv;
    wire co1;
    wire rom_addr0_r_n_5;
    wire rom_addr0_r_n_6;
    wire rom_addr0_r_6_inv;
    wire rom_addr0_r_5_inv;
    wire co2;
    wire rom_addr0_r_n_7;
    wire rom_addr0_r_7_inv;
    wire co3;
    wire rom_dout_11_ffin;
    wire rom_dout_10_ffin;
    wire rom_dout_9_ffin;
    wire rom_dout_8_ffin;
    wire rom_dout_7_ffin;
    wire rom_dout_6_ffin;
    wire rom_dout_5_ffin;
    wire rom_dout_4_ffin;
    wire rom_dout_3_ffin;
    wire rom_dout_2_ffin;
    wire rom_dout_1_ffin;
    wire rom_dout_ffin;
    wire rom_dout_23_ffin;
    wire rom_dout_22_ffin;
    wire rom_dout_21_ffin;
    wire rom_dout_20_ffin;
    wire rom_dout_19_ffin;
    wire rom_dout_18_ffin;
    wire rom_dout_17_ffin;
    wire rom_dout_16_ffin;
    wire rom_dout_15_ffin;
    wire rom_dout_14_ffin;
    wire rom_dout_13_ffin;
    wire rom_dout_12_ffin;
    wire rom_addr0_r_8;
    wire rom_addr0_r_9;
    wire rom_addr0_r_10;
    wire rom_addr0_r_11;
    wire rom_addr0_r_12;
    wire rom_addr0_r_13;
    wire rom_addr0_r_14;
    wire rom_addr0_r_15;
    wire rom_dout_s_n;
    wire rom_dout_inv;
    wire rom_dout_s_n_1;
    wire rom_dout_s_n_2;
    wire rom_dout_2_inv;
    wire rom_dout_1_inv;
    wire co0_1;
    wire rom_dout_s_n_3;
    wire rom_dout_s_n_4;
    wire rom_dout_4_inv;
    wire rom_dout_3_inv;
    wire co1_1;
    wire rom_dout_s_n_5;
    wire rom_dout_s_n_6;
    wire rom_dout_6_inv;
    wire rom_dout_5_inv;
    wire co2_1;
    wire rom_dout_s_n_7;
    wire rom_dout_s_n_8;
    wire rom_dout_8_inv;
    wire rom_dout_7_inv;
    wire co3_1;
    wire rom_dout_s_n_9;
    wire rom_dout_s_n_10;
    wire rom_dout_10_inv;
    wire rom_dout_9_inv;
    wire co4;
    wire rom_dout_s_n_11;
    wire rom_dout_11_inv;
    wire co5;
    wire rom_dout_c_n;
    wire rom_dout_12_inv;
    wire rom_dout_c_n_1;
    wire rom_dout_c_n_2;
    wire rom_dout_14_inv;
    wire rom_dout_13_inv;
    wire co0_2;
    wire rom_dout_c_n_3;
    wire rom_dout_c_n_4;
    wire rom_dout_16_inv;
    wire rom_dout_15_inv;
    wire co1_2;
    wire rom_dout_c_n_5;
    wire rom_dout_c_n_6;
    wire rom_dout_18_inv;
    wire rom_dout_17_inv;
    wire co2_2;
    wire rom_dout_c_n_7;
    wire rom_dout_c_n_8;
    wire rom_dout_20_inv;
    wire rom_dout_19_inv;
    wire co3_2;
    wire rom_dout_c_n_9;
    wire rom_dout_c_n_10;
    wire rom_dout_22_inv;
    wire rom_dout_21_inv;
    wire co4_1;
    wire rom_dout_c_n_11;
    wire scuba_vhi;
    wire scuba_vlo;
    wire rom_dout_23_inv;
    wire co5_1;

    INV INV_33 (.A(rom_addr0_r_7), .Z(rom_addr0_r_7_inv));

    INV INV_32 (.A(rom_addr0_r_6), .Z(rom_addr0_r_6_inv));

    INV INV_31 (.A(rom_addr0_r_5), .Z(rom_addr0_r_5_inv));

    INV INV_30 (.A(rom_addr0_r_4), .Z(rom_addr0_r_4_inv));

    INV INV_29 (.A(rom_addr0_r_3), .Z(rom_addr0_r_3_inv));

    INV INV_28 (.A(rom_addr0_r_2), .Z(rom_addr0_r_2_inv));

    INV INV_27 (.A(rom_addr0_r_1), .Z(rom_addr0_r_1_inv));

    INV INV_26 (.A(rom_addr0_r), .Z(rom_addr0_r_inv));

    XOR2 XOR2_t1 (.A(mx_ctrl_r), .B(mx_ctrl_r_1), .Z(cosromoutsel_i));

    INV INV_25 (.A(rom_dout_11), .Z(rom_dout_11_inv));

    INV INV_24 (.A(rom_dout_10), .Z(rom_dout_10_inv));

    INV INV_23 (.A(rom_dout_9), .Z(rom_dout_9_inv));

    INV INV_22 (.A(rom_dout_8), .Z(rom_dout_8_inv));

    INV INV_21 (.A(rom_dout_7), .Z(rom_dout_7_inv));

    INV INV_20 (.A(rom_dout_6), .Z(rom_dout_6_inv));

    INV INV_19 (.A(rom_dout_5), .Z(rom_dout_5_inv));

    INV INV_18 (.A(rom_dout_4), .Z(rom_dout_4_inv));

    INV INV_17 (.A(rom_dout_3), .Z(rom_dout_3_inv));

    INV INV_16 (.A(rom_dout_2), .Z(rom_dout_2_inv));

    INV INV_15 (.A(rom_dout_1), .Z(rom_dout_1_inv));

    INV INV_14 (.A(rom_dout), .Z(rom_dout_inv));

    INV INV_13 (.A(rom_dout_23), .Z(rom_dout_23_inv));

    INV INV_12 (.A(rom_dout_22), .Z(rom_dout_22_inv));

    INV INV_11 (.A(rom_dout_21), .Z(rom_dout_21_inv));

    INV INV_10 (.A(rom_dout_20), .Z(rom_dout_20_inv));

    INV INV_9 (.A(rom_dout_19), .Z(rom_dout_19_inv));

    INV INV_8 (.A(rom_dout_18), .Z(rom_dout_18_inv));

    INV INV_7 (.A(rom_dout_17), .Z(rom_dout_17_inv));

    INV INV_6 (.A(rom_dout_16), .Z(rom_dout_16_inv));

    INV INV_5 (.A(rom_dout_15), .Z(rom_dout_15_inv));

    INV INV_4 (.A(rom_dout_14), .Z(rom_dout_14_inv));

    INV INV_3 (.A(rom_dout_13), .Z(rom_dout_13_inv));

    INV INV_2 (.A(rom_dout_12), .Z(rom_dout_12_inv));

    defparam LUT4_2.initval =  16'hfffe ;
    ROM16X1A LUT4_2 (.AD3(rom_addr0_r_8), .AD2(rom_addr0_r_9), .AD1(rom_addr0_r_10), 
        .AD0(rom_addr0_r_11), .DO0(func_or_inet));

    defparam LUT4_1.initval =  16'hfffe ;
    ROM16X1A LUT4_1 (.AD3(rom_addr0_r_12), .AD2(rom_addr0_r_13), .AD1(rom_addr0_r_14), 
        .AD0(rom_addr0_r_15), .DO0(func_or_inet_1));

    defparam LUT4_0.initval =  16'hfffe ;
    ROM16X1A LUT4_0 (.AD3(func_or_inet), .AD2(func_or_inet_1), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(lx_ne0));

    INV INV_1 (.A(lx_ne0), .Z(lx_ne0_inv));

    AND2 AND2_t0 (.A(mx_ctrl_r), .B(lx_ne0_inv), .Z(out_sel_i));

    INV INV_0 (.A(mx_ctrl_r_1), .Z(mx_ctrl_r_1_inv));

    FD1P3DX FF_60 (.D(Theta[0]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_59 (.D(Theta[1]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_58 (.D(Theta[2]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_57 (.D(Theta[3]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_56 (.D(Theta[4]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_55 (.D(Theta[5]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_54 (.D(Theta[6]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_53 (.D(Theta[7]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_52 (.D(Theta[8]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(mx_ctrl_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_51 (.D(Theta[9]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(mx_ctrl_r_1))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_55 (.D0(rom_addr0_r), .D1(rom_addr0_r_n), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_8));

    MUX21 muxb_54 (.D0(rom_addr0_r_1), .D1(rom_addr0_r_n_1), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_9));

    MUX21 muxb_53 (.D0(rom_addr0_r_2), .D1(rom_addr0_r_n_2), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_10));

    MUX21 muxb_52 (.D0(rom_addr0_r_3), .D1(rom_addr0_r_n_3), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_11));

    MUX21 muxb_51 (.D0(rom_addr0_r_4), .D1(rom_addr0_r_n_4), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_12));

    MUX21 muxb_50 (.D0(rom_addr0_r_5), .D1(rom_addr0_r_n_5), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_13));

    MUX21 muxb_49 (.D0(rom_addr0_r_6), .D1(rom_addr0_r_n_6), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_14));

    MUX21 muxb_48 (.D0(rom_addr0_r_7), .D1(rom_addr0_r_n_7), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_15));

    FD1P3DX FF_50 (.D(rom_dout_11_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_49 (.D(rom_dout_10_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_48 (.D(rom_dout_9_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_47 (.D(rom_dout_8_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_46 (.D(rom_dout_7_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_45 (.D(rom_dout_6_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_44 (.D(rom_dout_5_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_43 (.D(rom_dout_4_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_42 (.D(rom_dout_3_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_41 (.D(rom_dout_2_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_40 (.D(rom_dout_1_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_39 (.D(rom_dout_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_38 (.D(rom_dout_23_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_23))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_37 (.D(rom_dout_22_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_22))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_36 (.D(rom_dout_21_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_21))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_35 (.D(rom_dout_20_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_20))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_34 (.D(rom_dout_19_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_19))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_33 (.D(rom_dout_18_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_18))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_32 (.D(rom_dout_17_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_17))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_31 (.D(rom_dout_16_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_16))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_30 (.D(rom_dout_15_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_15))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_29 (.D(rom_dout_14_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(rom_dout_13_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(rom_dout_12_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(cosromoutsel_i), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(cosromoutsel))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(mx_ctrl_r_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(sinromoutsel))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_47 (.D0(rom_dout), .D1(rom_dout_s_n), .SD(sinromoutsel), 
        .Z(rom_dout_s));

    MUX21 muxb_46 (.D0(rom_dout_1), .D1(rom_dout_s_n_1), .SD(sinromoutsel), 
        .Z(rom_dout_s_1));

    MUX21 muxb_45 (.D0(rom_dout_2), .D1(rom_dout_s_n_2), .SD(sinromoutsel), 
        .Z(rom_dout_s_2));

    MUX21 muxb_44 (.D0(rom_dout_3), .D1(rom_dout_s_n_3), .SD(sinromoutsel), 
        .Z(rom_dout_s_3));

    MUX21 muxb_43 (.D0(rom_dout_4), .D1(rom_dout_s_n_4), .SD(sinromoutsel), 
        .Z(rom_dout_s_4));

    MUX21 muxb_42 (.D0(rom_dout_5), .D1(rom_dout_s_n_5), .SD(sinromoutsel), 
        .Z(rom_dout_s_5));

    MUX21 muxb_41 (.D0(rom_dout_6), .D1(rom_dout_s_n_6), .SD(sinromoutsel), 
        .Z(rom_dout_s_6));

    MUX21 muxb_40 (.D0(rom_dout_7), .D1(rom_dout_s_n_7), .SD(sinromoutsel), 
        .Z(rom_dout_s_7));

    MUX21 muxb_39 (.D0(rom_dout_8), .D1(rom_dout_s_n_8), .SD(sinromoutsel), 
        .Z(rom_dout_s_8));

    MUX21 muxb_38 (.D0(rom_dout_9), .D1(rom_dout_s_n_9), .SD(sinromoutsel), 
        .Z(rom_dout_s_9));

    MUX21 muxb_37 (.D0(rom_dout_10), .D1(rom_dout_s_n_10), .SD(sinromoutsel), 
        .Z(rom_dout_s_10));

    MUX21 muxb_36 (.D0(rom_dout_11), .D1(rom_dout_s_n_11), .SD(sinromoutsel), 
        .Z(rom_dout_s_11));

    MUX21 muxb_35 (.D0(rom_dout_12), .D1(rom_dout_c_n), .SD(cosromoutsel), 
        .Z(rom_dout_c));

    MUX21 muxb_34 (.D0(rom_dout_13), .D1(rom_dout_c_n_1), .SD(cosromoutsel), 
        .Z(rom_dout_c_1));

    MUX21 muxb_33 (.D0(rom_dout_14), .D1(rom_dout_c_n_2), .SD(cosromoutsel), 
        .Z(rom_dout_c_2));

    MUX21 muxb_32 (.D0(rom_dout_15), .D1(rom_dout_c_n_3), .SD(cosromoutsel), 
        .Z(rom_dout_c_3));

    MUX21 muxb_31 (.D0(rom_dout_16), .D1(rom_dout_c_n_4), .SD(cosromoutsel), 
        .Z(rom_dout_c_4));

    MUX21 muxb_30 (.D0(rom_dout_17), .D1(rom_dout_c_n_5), .SD(cosromoutsel), 
        .Z(rom_dout_c_5));

    MUX21 muxb_29 (.D0(rom_dout_18), .D1(rom_dout_c_n_6), .SD(cosromoutsel), 
        .Z(rom_dout_c_6));

    MUX21 muxb_28 (.D0(rom_dout_19), .D1(rom_dout_c_n_7), .SD(cosromoutsel), 
        .Z(rom_dout_c_7));

    MUX21 muxb_27 (.D0(rom_dout_20), .D1(rom_dout_c_n_8), .SD(cosromoutsel), 
        .Z(rom_dout_c_8));

    MUX21 muxb_26 (.D0(rom_dout_21), .D1(rom_dout_c_n_9), .SD(cosromoutsel), 
        .Z(rom_dout_c_9));

    MUX21 muxb_25 (.D0(rom_dout_22), .D1(rom_dout_c_n_10), .SD(cosromoutsel), 
        .Z(rom_dout_c_10));

    MUX21 muxb_24 (.D0(rom_dout_23), .D1(rom_dout_c_n_11), .SD(cosromoutsel), 
        .Z(rom_dout_c_11));

    FD1P3DX FF_24 (.D(out_sel_i), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(out_sel))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_23 (.D0(rom_dout_s), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre));

    MUX21 muxb_22 (.D0(rom_dout_s_1), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_1));

    MUX21 muxb_21 (.D0(rom_dout_s_2), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_2));

    MUX21 muxb_20 (.D0(rom_dout_s_3), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_3));

    MUX21 muxb_19 (.D0(rom_dout_s_4), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_4));

    MUX21 muxb_18 (.D0(rom_dout_s_5), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_5));

    MUX21 muxb_17 (.D0(rom_dout_s_6), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_6));

    MUX21 muxb_16 (.D0(rom_dout_s_7), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_7));

    MUX21 muxb_15 (.D0(rom_dout_s_8), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_8));

    MUX21 muxb_14 (.D0(rom_dout_s_9), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_9));

    MUX21 muxb_13 (.D0(rom_dout_s_10), .D1(scuba_vhi), .SD(out_sel), .Z(sinout_pre_10));

    MUX21 muxb_12 (.D0(rom_dout_s_11), .D1(mx_ctrl_r_1), .SD(out_sel), .Z(sinout_pre_11));

    MUX21 muxb_11 (.D0(rom_dout_c), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre));

    MUX21 muxb_10 (.D0(rom_dout_c_1), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_1));

    MUX21 muxb_9 (.D0(rom_dout_c_2), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_2));

    MUX21 muxb_8 (.D0(rom_dout_c_3), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_3));

    MUX21 muxb_7 (.D0(rom_dout_c_4), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_4));

    MUX21 muxb_6 (.D0(rom_dout_c_5), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_5));

    MUX21 muxb_5 (.D0(rom_dout_c_6), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_6));

    MUX21 muxb_4 (.D0(rom_dout_c_7), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_7));

    MUX21 muxb_3 (.D0(rom_dout_c_8), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_8));

    MUX21 muxb_2 (.D0(rom_dout_c_9), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_9));

    MUX21 muxb_1 (.D0(rom_dout_c_10), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_10));

    MUX21 muxb_0 (.D0(rom_dout_c_11), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_11));

    FD1P3DX FF_23 (.D(sinout_pre), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(Sine[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(sinout_pre_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(sinout_pre_2), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(sinout_pre_3), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(sinout_pre_4), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(sinout_pre_5), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(sinout_pre_6), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(sinout_pre_7), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(sinout_pre_8), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(sinout_pre_9), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[9]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(sinout_pre_10), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[10]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(sinout_pre_11), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[11]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(cosout_pre), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(Cosine[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(cosout_pre_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(cosout_pre_2), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(cosout_pre_3), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(cosout_pre_4), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(cosout_pre_5), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(cosout_pre_6), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(cosout_pre_7), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(cosout_pre_8), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(cosout_pre_9), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[9]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(cosout_pre_10), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[10]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(cosout_pre_11), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[11]))
             /* synthesis GSR="ENABLED" */;

    defparam neg_rom_addr0_r_n_0.INJECT1_1 = "NO" ;
    defparam neg_rom_addr0_r_n_0.INJECT1_0 = "NO" ;
    defparam neg_rom_addr0_r_n_0.INIT1 =  16'h66AA ;
    defparam neg_rom_addr0_r_n_0.INIT0 =  16'h66AA ;
    CCU2C neg_rom_addr0_r_n_0 (.A0(scuba_vlo), .A1(rom_addr0_r_inv), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(rom_addr0_r_n), .COUT(co0));

    defparam neg_rom_addr0_r_n_1.INJECT1_1 = "NO" ;
    defparam neg_rom_addr0_r_n_1.INJECT1_0 = "NO" ;
    defparam neg_rom_addr0_r_n_1.INIT1 =  16'h66AA ;
    defparam neg_rom_addr0_r_n_1.INIT0 =  16'h66AA ;
    CCU2C neg_rom_addr0_r_n_1 (.A0(rom_addr0_r_1_inv), .A1(rom_addr0_r_2_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co0), .S0(rom_addr0_r_n_1), 
        .S1(rom_addr0_r_n_2), .COUT(co1));

    defparam neg_rom_addr0_r_n_2.INJECT1_1 = "NO" ;
    defparam neg_rom_addr0_r_n_2.INJECT1_0 = "NO" ;
    defparam neg_rom_addr0_r_n_2.INIT1 =  16'h66AA ;
    defparam neg_rom_addr0_r_n_2.INIT0 =  16'h66AA ;
    CCU2C neg_rom_addr0_r_n_2 (.A0(rom_addr0_r_3_inv), .A1(rom_addr0_r_4_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co1), .S0(rom_addr0_r_n_3), 
        .S1(rom_addr0_r_n_4), .COUT(co2));

    defparam neg_rom_addr0_r_n_3.INJECT1_1 = "NO" ;
    defparam neg_rom_addr0_r_n_3.INJECT1_0 = "NO" ;
    defparam neg_rom_addr0_r_n_3.INIT1 =  16'h66AA ;
    defparam neg_rom_addr0_r_n_3.INIT0 =  16'h66AA ;
    CCU2C neg_rom_addr0_r_n_3 (.A0(rom_addr0_r_5_inv), .A1(rom_addr0_r_6_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co2), .S0(rom_addr0_r_n_5), 
        .S1(rom_addr0_r_n_6), .COUT(co3));

    defparam neg_rom_addr0_r_n_4.INJECT1_1 = "NO" ;
    defparam neg_rom_addr0_r_n_4.INJECT1_0 = "NO" ;
    defparam neg_rom_addr0_r_n_4.INIT1 =  16'h66AA ;
    defparam neg_rom_addr0_r_n_4.INIT0 =  16'h66AA ;
    CCU2C neg_rom_addr0_r_n_4 (.A0(rom_addr0_r_7_inv), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3), .S0(rom_addr0_r_n_7), .S1(), .COUT());

    defparam triglut_1_0_23.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    ROM256X1A triglut_1_0_23 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_11_ffin));

    defparam triglut_1_0_22.initval = 256'hF800000000000000000000000000000000000000000000000000000000000000 ;
    ROM256X1A triglut_1_0_22 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_10_ffin));

    defparam triglut_1_0_21.initval = 256'h07FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC000000000000000000000 ;
    ROM256X1A triglut_1_0_21 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_9_ffin));

    defparam triglut_1_0_20.initval = 256'h07FFFFFFFFFFFFFFFFFFFFFFFFFFF80000000000003FFFFFFFFFFC0000000000 ;
    ROM256X1A triglut_1_0_20 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_8_ffin));

    defparam triglut_1_0_19.initval = 256'h07FFFFFFFFFFFFFFFFFFC000000007FFFFFFC000003FFFFF800003FFFFE00000 ;
    ROM256X1A triglut_1_0_19 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_7_ffin));

    defparam triglut_1_0_18.initval = 256'h07FFFFFFFFFFFFC000003FFFF80007FFF0003FFC003FFC007FF003FF801FF800 ;
    ROM256X1A triglut_1_0_18 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_6_ffin));

    defparam triglut_1_0_17.initval = 256'h07FFFFFFFF80003FFE003FF007F807F80FE03F03F03F03E07C0F83F07C1F07C0 ;
    ROM256X1A triglut_1_0_17 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_5_ffin));

    defparam triglut_1_0_16.initval = 256'h07FFFFF8007FC03F81F83E0F8787C7878F1C38E38E38E39C738C738C639CE738 ;
    ROM256X1A triglut_1_0_16 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_4_ffin));

    defparam triglut_1_0_15.initval = 256'h07FFF807E0783C3871C639CC666726664C9B24DB6DB6D25B4B4B4B4B5A52D6B4 ;
    ROM256X1A triglut_1_0_15 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_3_ffin));

    defparam triglut_1_0_14.initval = 256'h07FE07871C6733264925A52A555695552A529692DB6499326666666633398CE6 ;
    ROM256X1A triglut_1_0_14 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_2_ffin));

    defparam triglut_1_0_13.initval = 256'h07E1C666DA56AAB52D93338F0FFC3FF078E73336492D2B56AAAAAAAAD54AB56A ;
    ROM256X1A triglut_1_0_13 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_1_ffin));

    defparam triglut_1_0_12.initval = 256'h07192554933C001C64B5549330FC3F8E6494AAA52C998E3C1FFFFFC07C1E1E3C ;
    ROM256X1A triglut_1_0_12 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_ffin));

    defparam triglut_1_0_11.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    ROM256X1A triglut_1_0_11 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_23_ffin));

    defparam triglut_1_0_10.initval = 256'h000000000000000000000000000000000000000000000000000000000000003F ;
    ROM256X1A triglut_1_0_10 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_22_ffin));

    defparam triglut_1_0_9.initval = 256'h0000000000000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0 ;
    ROM256X1A triglut_1_0_9 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_21_ffin));

    defparam triglut_1_0_8.initval = 256'h00000000007FFFFFFFFFF80000000000003FFFFFFFFFFFFFFFFFFFFFFFFFFFC0 ;
    ROM256X1A triglut_1_0_8 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_20_ffin));

    defparam triglut_1_0_7.initval = 256'h00000FFFFF800003FFFFF8000007FFFFFFC000000007FFFFFFFFFFFFFFFFFFC0 ;
    ROM256X1A triglut_1_0_7 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_19_ffin));

    defparam triglut_1_0_6.initval = 256'h003FF003FF801FFC007FF8007FF8001FFFC0003FFFF8000007FFFFFFFFFFFFC0 ;
    ROM256X1A triglut_1_0_6 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_18_ffin));

    defparam triglut_1_0_5.initval = 256'h07C1F07C1F83E07C0F81F81F81F80FE03FC03FC01FF800FFF80003FFFFFFFFC0 ;
    ROM256X1A triglut_1_0_5 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_17_ffin));

    defparam triglut_1_0_4.initval = 256'h39CE738C639C639C738E38E38E3871E3C3C7C3C3E0F83F03F807FC003FFFFFC0 ;
    ROM256X1A triglut_1_0_4 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_16_ffin));

    defparam triglut_1_0_3.initval = 256'h5AD694B5A5A5A5A5B496DB6DB649B264CCC9CCCC6738C71C38783C0FC03FFFC0 ;
    ROM256X1A triglut_1_0_3 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_15_ffin));

    defparam triglut_1_0_2.initval = 256'hCE633998CCCCCCCC99324DB692D294A95552D554A94B4924C999CC71C3C0FFC0 ;
    ROM256X1A triglut_1_0_2 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_14_ffin));

    defparam triglut_1_0_1.initval = 256'hAD5AA556AAAAAAAAD5A96924D999CE3C1FF87FE1E39993695AAAD4B6CCC70FC0 ;
    ROM256X1A triglut_1_0_1 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_13_ffin));

    defparam triglut_1_0_0.initval = 256'h78F0F07C07FFFFF078E332694AAA524CE3F87E1992555A4C70007992554931C0 ;
    ROM256X1A triglut_1_0_0 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_12_ffin));

    defparam neg_rom_dout_s_n_0.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_s_n_0.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_s_n_0.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_s_n_0.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_s_n_0 (.A0(scuba_vlo), .A1(rom_dout_inv), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(rom_dout_s_n), .COUT(co0_1));

    defparam neg_rom_dout_s_n_1.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_s_n_1.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_s_n_1.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_s_n_1.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_s_n_1 (.A0(rom_dout_1_inv), .A1(rom_dout_2_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co0_1), .S0(rom_dout_s_n_1), 
        .S1(rom_dout_s_n_2), .COUT(co1_1));

    defparam neg_rom_dout_s_n_2.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_s_n_2.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_s_n_2.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_s_n_2.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_s_n_2 (.A0(rom_dout_3_inv), .A1(rom_dout_4_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co1_1), .S0(rom_dout_s_n_3), 
        .S1(rom_dout_s_n_4), .COUT(co2_1));

    defparam neg_rom_dout_s_n_3.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_s_n_3.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_s_n_3.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_s_n_3.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_s_n_3 (.A0(rom_dout_5_inv), .A1(rom_dout_6_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co2_1), .S0(rom_dout_s_n_5), 
        .S1(rom_dout_s_n_6), .COUT(co3_1));

    defparam neg_rom_dout_s_n_4.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_s_n_4.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_s_n_4.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_s_n_4.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_s_n_4 (.A0(rom_dout_7_inv), .A1(rom_dout_8_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co3_1), .S0(rom_dout_s_n_7), 
        .S1(rom_dout_s_n_8), .COUT(co4));

    defparam neg_rom_dout_s_n_5.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_s_n_5.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_s_n_5.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_s_n_5.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_s_n_5 (.A0(rom_dout_9_inv), .A1(rom_dout_10_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co4), .S0(rom_dout_s_n_9), 
        .S1(rom_dout_s_n_10), .COUT(co5));

    defparam neg_rom_dout_s_n_6.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_s_n_6.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_s_n_6.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_s_n_6.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_s_n_6 (.A0(rom_dout_11_inv), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co5), .S0(rom_dout_s_n_11), .S1(), .COUT());

    defparam neg_rom_dout_c_n_0.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_c_n_0.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_c_n_0.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_c_n_0.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_c_n_0 (.A0(scuba_vlo), .A1(rom_dout_12_inv), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(rom_dout_c_n), .COUT(co0_2));

    defparam neg_rom_dout_c_n_1.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_c_n_1.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_c_n_1.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_c_n_1.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_c_n_1 (.A0(rom_dout_13_inv), .A1(rom_dout_14_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co0_2), .S0(rom_dout_c_n_1), 
        .S1(rom_dout_c_n_2), .COUT(co1_2));

    defparam neg_rom_dout_c_n_2.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_c_n_2.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_c_n_2.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_c_n_2.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_c_n_2 (.A0(rom_dout_15_inv), .A1(rom_dout_16_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co1_2), .S0(rom_dout_c_n_3), 
        .S1(rom_dout_c_n_4), .COUT(co2_2));

    defparam neg_rom_dout_c_n_3.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_c_n_3.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_c_n_3.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_c_n_3.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_c_n_3 (.A0(rom_dout_17_inv), .A1(rom_dout_18_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co2_2), .S0(rom_dout_c_n_5), 
        .S1(rom_dout_c_n_6), .COUT(co3_2));

    defparam neg_rom_dout_c_n_4.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_c_n_4.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_c_n_4.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_c_n_4.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_c_n_4 (.A0(rom_dout_19_inv), .A1(rom_dout_20_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co3_2), .S0(rom_dout_c_n_7), 
        .S1(rom_dout_c_n_8), .COUT(co4_1));

    defparam neg_rom_dout_c_n_5.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_c_n_5.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_c_n_5.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_c_n_5.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_c_n_5 (.A0(rom_dout_21_inv), .A1(rom_dout_22_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co4_1), .S0(rom_dout_c_n_9), 
        .S1(rom_dout_c_n_10), .COUT(co5_1));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam neg_rom_dout_c_n_6.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_c_n_6.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_c_n_6.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_c_n_6.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_c_n_6 (.A0(rom_dout_23_inv), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co5_1), .S0(rom_dout_c_n_11), .S1(), .COUT());



    // exemplar begin
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
