PROJECT: rcosfilter_m
working_path: "syn_tmp"
module: rcosfilter_m
verilog_file_list: "C:/lscc/diamond/3.14/cae_library/synthesis/verilog/ecp5um5g.v"
verilog_file_list: "../rcosfilter_m.v"
verilog_file_list: "../rcosfilter_m_core_bb.v"
resource_sharing: false
write_verilog: true
write_vhdl: false
suffix_name: edi
output_file_name: rcosfilter_m
write_prf: false
vlog_std_v2001: true
disable_io_insertion: true
force_gsr: false
speed_grade: 8
frequency: 125.000
fanout_limit: 100
retiming: false
pipe: false
fixgatedclocks: 0
fixgeneratedclocks: 0
