/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Sun Jan 04 00:06:49 2026 */

/* parameterized module instance */
pll_try __ (.CLKI( ), .CLKOP( ));
