/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Sun Jan 04 00:12:37 2026 */

/* parameterized module instance */
pll_24_64m __ (.CLKI( ), .RST( ), .CLKOP( ), .LOCK( ));
