/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 1.6 */
/* C:\lscc\diamond\3.14\ispfpga\bin\nt64\scuba.exe -w -n sincos_m -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00g -type cosine -addr_width 10 -width 8 -pfu -input_reg -input_reg -mode 6 -output_reg -area -pipeline 1 -fdc C:/Users/SNA/Documents/FPGA_code/lattice_sdr_code/creating_nco/sincos_m/sincos_m.fdc  */
/* Wed Jan 07 23:44:27 2026 */


`timescale 1 ns / 1 ps
module sincos_m (Clock, ClkEn, Reset, Theta, Sine, Cosine)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClkEn;
    input wire Reset;
    input wire [9:0] Theta;
    output wire [7:0] Sine;
    output wire [7:0] Cosine;

    wire func_or_inet_1;
    wire func_or_inet;
    wire lx_ne0;
    wire lx_ne0_inv;
    wire mx_ctrl_r_1_inv;
    wire rom_addr0_r;
    wire rom_addr0_r_1;
    wire rom_addr0_r_2;
    wire rom_addr0_r_3;
    wire rom_addr0_r_4;
    wire rom_addr0_r_5;
    wire rom_addr0_r_6;
    wire mx_ctrl_r;
    wire rom_addr0_r_7;
    wire cosromoutsel_i;
    wire rom_dout;
    wire rom_dout_1;
    wire rom_dout_2;
    wire rom_dout_3;
    wire rom_dout_4;
    wire rom_dout_5;
    wire rom_dout_6;
    wire sinromoutsel;
    wire rom_dout_7;
    wire rom_dout_8;
    wire rom_dout_9;
    wire rom_dout_10;
    wire rom_dout_11;
    wire rom_dout_12;
    wire rom_dout_13;
    wire rom_dout_14;
    wire cosromoutsel;
    wire rom_dout_15;
    wire out_sel_i;
    wire rom_dout_s;
    wire rom_dout_s_1;
    wire rom_dout_s_2;
    wire rom_dout_s_3;
    wire rom_dout_s_4;
    wire rom_dout_s_5;
    wire rom_dout_s_6;
    wire mx_ctrl_r_1;
    wire rom_dout_s_7;
    wire rom_dout_c;
    wire rom_dout_c_1;
    wire rom_dout_c_2;
    wire rom_dout_c_3;
    wire rom_dout_c_4;
    wire rom_dout_c_5;
    wire rom_dout_c_6;
    wire out_sel;
    wire rom_dout_c_7;
    wire sinout_pre;
    wire sinout_pre_1;
    wire sinout_pre_2;
    wire sinout_pre_3;
    wire sinout_pre_4;
    wire sinout_pre_5;
    wire sinout_pre_6;
    wire sinout_pre_7;
    wire cosout_pre;
    wire cosout_pre_1;
    wire cosout_pre_2;
    wire cosout_pre_3;
    wire cosout_pre_4;
    wire cosout_pre_5;
    wire cosout_pre_6;
    wire cosout_pre_7;
    wire rom_addr0_r_n;
    wire rom_addr0_r_inv;
    wire rom_addr0_r_n_1;
    wire rom_addr0_r_n_2;
    wire rom_addr0_r_2_inv;
    wire rom_addr0_r_1_inv;
    wire co0;
    wire rom_addr0_r_n_3;
    wire rom_addr0_r_n_4;
    wire rom_addr0_r_4_inv;
    wire rom_addr0_r_3_inv;
    wire co1;
    wire rom_addr0_r_n_5;
    wire rom_addr0_r_n_6;
    wire rom_addr0_r_6_inv;
    wire rom_addr0_r_5_inv;
    wire co2;
    wire rom_addr0_r_n_7;
    wire rom_addr0_r_7_inv;
    wire co3;
    wire rom_dout_7_ffin;
    wire rom_dout_6_ffin;
    wire rom_dout_5_ffin;
    wire rom_dout_4_ffin;
    wire rom_dout_3_ffin;
    wire rom_dout_2_ffin;
    wire rom_dout_1_ffin;
    wire rom_dout_ffin;
    wire rom_dout_15_ffin;
    wire rom_dout_14_ffin;
    wire rom_dout_13_ffin;
    wire rom_dout_12_ffin;
    wire rom_dout_11_ffin;
    wire rom_dout_10_ffin;
    wire rom_dout_9_ffin;
    wire rom_dout_8_ffin;
    wire rom_addr0_r_8;
    wire rom_addr0_r_9;
    wire rom_addr0_r_10;
    wire rom_addr0_r_11;
    wire rom_addr0_r_12;
    wire rom_addr0_r_13;
    wire rom_addr0_r_14;
    wire rom_addr0_r_15;
    wire rom_dout_s_n;
    wire rom_dout_inv;
    wire rom_dout_s_n_1;
    wire rom_dout_s_n_2;
    wire rom_dout_2_inv;
    wire rom_dout_1_inv;
    wire co0_1;
    wire rom_dout_s_n_3;
    wire rom_dout_s_n_4;
    wire rom_dout_4_inv;
    wire rom_dout_3_inv;
    wire co1_1;
    wire rom_dout_s_n_5;
    wire rom_dout_s_n_6;
    wire rom_dout_6_inv;
    wire rom_dout_5_inv;
    wire co2_1;
    wire rom_dout_s_n_7;
    wire rom_dout_7_inv;
    wire co3_1;
    wire rom_dout_c_n;
    wire rom_dout_8_inv;
    wire rom_dout_c_n_1;
    wire rom_dout_c_n_2;
    wire rom_dout_10_inv;
    wire rom_dout_9_inv;
    wire co0_2;
    wire rom_dout_c_n_3;
    wire rom_dout_c_n_4;
    wire rom_dout_12_inv;
    wire rom_dout_11_inv;
    wire co1_2;
    wire rom_dout_c_n_5;
    wire rom_dout_c_n_6;
    wire rom_dout_14_inv;
    wire rom_dout_13_inv;
    wire co2_2;
    wire rom_dout_c_n_7;
    wire scuba_vhi;
    wire scuba_vlo;
    wire rom_dout_15_inv;
    wire co3_2;

    INV INV_25 (.A(rom_addr0_r_7), .Z(rom_addr0_r_7_inv));

    INV INV_24 (.A(rom_addr0_r_6), .Z(rom_addr0_r_6_inv));

    INV INV_23 (.A(rom_addr0_r_5), .Z(rom_addr0_r_5_inv));

    INV INV_22 (.A(rom_addr0_r_4), .Z(rom_addr0_r_4_inv));

    INV INV_21 (.A(rom_addr0_r_3), .Z(rom_addr0_r_3_inv));

    INV INV_20 (.A(rom_addr0_r_2), .Z(rom_addr0_r_2_inv));

    INV INV_19 (.A(rom_addr0_r_1), .Z(rom_addr0_r_1_inv));

    INV INV_18 (.A(rom_addr0_r), .Z(rom_addr0_r_inv));

    XOR2 XOR2_t1 (.A(mx_ctrl_r), .B(mx_ctrl_r_1), .Z(cosromoutsel_i));

    INV INV_17 (.A(rom_dout_7), .Z(rom_dout_7_inv));

    INV INV_16 (.A(rom_dout_6), .Z(rom_dout_6_inv));

    INV INV_15 (.A(rom_dout_5), .Z(rom_dout_5_inv));

    INV INV_14 (.A(rom_dout_4), .Z(rom_dout_4_inv));

    INV INV_13 (.A(rom_dout_3), .Z(rom_dout_3_inv));

    INV INV_12 (.A(rom_dout_2), .Z(rom_dout_2_inv));

    INV INV_11 (.A(rom_dout_1), .Z(rom_dout_1_inv));

    INV INV_10 (.A(rom_dout), .Z(rom_dout_inv));

    INV INV_9 (.A(rom_dout_15), .Z(rom_dout_15_inv));

    INV INV_8 (.A(rom_dout_14), .Z(rom_dout_14_inv));

    INV INV_7 (.A(rom_dout_13), .Z(rom_dout_13_inv));

    INV INV_6 (.A(rom_dout_12), .Z(rom_dout_12_inv));

    INV INV_5 (.A(rom_dout_11), .Z(rom_dout_11_inv));

    INV INV_4 (.A(rom_dout_10), .Z(rom_dout_10_inv));

    INV INV_3 (.A(rom_dout_9), .Z(rom_dout_9_inv));

    INV INV_2 (.A(rom_dout_8), .Z(rom_dout_8_inv));

    defparam LUT4_2.initval =  16'hfffe ;
    ROM16X1A LUT4_2 (.AD3(rom_addr0_r_8), .AD2(rom_addr0_r_9), .AD1(rom_addr0_r_10), 
        .AD0(rom_addr0_r_11), .DO0(func_or_inet));

    defparam LUT4_1.initval =  16'hfffe ;
    ROM16X1A LUT4_1 (.AD3(rom_addr0_r_12), .AD2(rom_addr0_r_13), .AD1(rom_addr0_r_14), 
        .AD0(rom_addr0_r_15), .DO0(func_or_inet_1));

    defparam LUT4_0.initval =  16'hfffe ;
    ROM16X1A LUT4_0 (.AD3(func_or_inet), .AD2(func_or_inet_1), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(lx_ne0));

    INV INV_1 (.A(lx_ne0), .Z(lx_ne0_inv));

    AND2 AND2_t0 (.A(mx_ctrl_r), .B(lx_ne0_inv), .Z(out_sel_i));

    INV INV_0 (.A(mx_ctrl_r_1), .Z(mx_ctrl_r_1_inv));

    FD1P3DX FF_44 (.D(Theta[0]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_43 (.D(Theta[1]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_42 (.D(Theta[2]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_41 (.D(Theta[3]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_40 (.D(Theta[4]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_39 (.D(Theta[5]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_38 (.D(Theta[6]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_37 (.D(Theta[7]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_36 (.D(Theta[8]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(mx_ctrl_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_35 (.D(Theta[9]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(mx_ctrl_r_1))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_39 (.D0(rom_addr0_r), .D1(rom_addr0_r_n), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_8));

    MUX21 muxb_38 (.D0(rom_addr0_r_1), .D1(rom_addr0_r_n_1), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_9));

    MUX21 muxb_37 (.D0(rom_addr0_r_2), .D1(rom_addr0_r_n_2), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_10));

    MUX21 muxb_36 (.D0(rom_addr0_r_3), .D1(rom_addr0_r_n_3), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_11));

    MUX21 muxb_35 (.D0(rom_addr0_r_4), .D1(rom_addr0_r_n_4), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_12));

    MUX21 muxb_34 (.D0(rom_addr0_r_5), .D1(rom_addr0_r_n_5), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_13));

    MUX21 muxb_33 (.D0(rom_addr0_r_6), .D1(rom_addr0_r_n_6), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_14));

    MUX21 muxb_32 (.D0(rom_addr0_r_7), .D1(rom_addr0_r_n_7), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_15));

    FD1P3DX FF_34 (.D(rom_dout_7_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_33 (.D(rom_dout_6_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_32 (.D(rom_dout_5_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_31 (.D(rom_dout_4_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_30 (.D(rom_dout_3_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_29 (.D(rom_dout_2_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(rom_dout_1_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(rom_dout_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(rom_dout_15_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_15))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(rom_dout_14_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(rom_dout_13_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(rom_dout_12_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(rom_dout_11_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(rom_dout_10_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(rom_dout_9_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(rom_dout_8_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(cosromoutsel_i), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(cosromoutsel))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(mx_ctrl_r_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(sinromoutsel))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_31 (.D0(rom_dout), .D1(rom_dout_s_n), .SD(sinromoutsel), 
        .Z(rom_dout_s));

    MUX21 muxb_30 (.D0(rom_dout_1), .D1(rom_dout_s_n_1), .SD(sinromoutsel), 
        .Z(rom_dout_s_1));

    MUX21 muxb_29 (.D0(rom_dout_2), .D1(rom_dout_s_n_2), .SD(sinromoutsel), 
        .Z(rom_dout_s_2));

    MUX21 muxb_28 (.D0(rom_dout_3), .D1(rom_dout_s_n_3), .SD(sinromoutsel), 
        .Z(rom_dout_s_3));

    MUX21 muxb_27 (.D0(rom_dout_4), .D1(rom_dout_s_n_4), .SD(sinromoutsel), 
        .Z(rom_dout_s_4));

    MUX21 muxb_26 (.D0(rom_dout_5), .D1(rom_dout_s_n_5), .SD(sinromoutsel), 
        .Z(rom_dout_s_5));

    MUX21 muxb_25 (.D0(rom_dout_6), .D1(rom_dout_s_n_6), .SD(sinromoutsel), 
        .Z(rom_dout_s_6));

    MUX21 muxb_24 (.D0(rom_dout_7), .D1(rom_dout_s_n_7), .SD(sinromoutsel), 
        .Z(rom_dout_s_7));

    MUX21 muxb_23 (.D0(rom_dout_8), .D1(rom_dout_c_n), .SD(cosromoutsel), 
        .Z(rom_dout_c));

    MUX21 muxb_22 (.D0(rom_dout_9), .D1(rom_dout_c_n_1), .SD(cosromoutsel), 
        .Z(rom_dout_c_1));

    MUX21 muxb_21 (.D0(rom_dout_10), .D1(rom_dout_c_n_2), .SD(cosromoutsel), 
        .Z(rom_dout_c_2));

    MUX21 muxb_20 (.D0(rom_dout_11), .D1(rom_dout_c_n_3), .SD(cosromoutsel), 
        .Z(rom_dout_c_3));

    MUX21 muxb_19 (.D0(rom_dout_12), .D1(rom_dout_c_n_4), .SD(cosromoutsel), 
        .Z(rom_dout_c_4));

    MUX21 muxb_18 (.D0(rom_dout_13), .D1(rom_dout_c_n_5), .SD(cosromoutsel), 
        .Z(rom_dout_c_5));

    MUX21 muxb_17 (.D0(rom_dout_14), .D1(rom_dout_c_n_6), .SD(cosromoutsel), 
        .Z(rom_dout_c_6));

    MUX21 muxb_16 (.D0(rom_dout_15), .D1(rom_dout_c_n_7), .SD(cosromoutsel), 
        .Z(rom_dout_c_7));

    FD1P3DX FF_16 (.D(out_sel_i), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(out_sel))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_15 (.D0(rom_dout_s), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre));

    MUX21 muxb_14 (.D0(rom_dout_s_1), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_1));

    MUX21 muxb_13 (.D0(rom_dout_s_2), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_2));

    MUX21 muxb_12 (.D0(rom_dout_s_3), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_3));

    MUX21 muxb_11 (.D0(rom_dout_s_4), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_4));

    MUX21 muxb_10 (.D0(rom_dout_s_5), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_5));

    MUX21 muxb_9 (.D0(rom_dout_s_6), .D1(scuba_vhi), .SD(out_sel), .Z(sinout_pre_6));

    MUX21 muxb_8 (.D0(rom_dout_s_7), .D1(mx_ctrl_r_1), .SD(out_sel), .Z(sinout_pre_7));

    MUX21 muxb_7 (.D0(rom_dout_c), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre));

    MUX21 muxb_6 (.D0(rom_dout_c_1), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_1));

    MUX21 muxb_5 (.D0(rom_dout_c_2), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_2));

    MUX21 muxb_4 (.D0(rom_dout_c_3), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_3));

    MUX21 muxb_3 (.D0(rom_dout_c_4), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_4));

    MUX21 muxb_2 (.D0(rom_dout_c_5), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_5));

    MUX21 muxb_1 (.D0(rom_dout_c_6), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_6));

    MUX21 muxb_0 (.D0(rom_dout_c_7), .D1(scuba_vlo), .SD(out_sel), .Z(cosout_pre_7));

    FD1P3DX FF_15 (.D(sinout_pre), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(Sine[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(sinout_pre_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(sinout_pre_2), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(sinout_pre_3), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(sinout_pre_4), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(sinout_pre_5), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(sinout_pre_6), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(sinout_pre_7), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(cosout_pre), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(Cosine[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(cosout_pre_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(cosout_pre_2), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(cosout_pre_3), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(cosout_pre_4), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(cosout_pre_5), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(cosout_pre_6), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(cosout_pre_7), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[7]))
             /* synthesis GSR="ENABLED" */;

    defparam neg_rom_addr0_r_n_0.INJECT1_1 = "NO" ;
    defparam neg_rom_addr0_r_n_0.INJECT1_0 = "NO" ;
    defparam neg_rom_addr0_r_n_0.INIT1 =  16'h66AA ;
    defparam neg_rom_addr0_r_n_0.INIT0 =  16'h66AA ;
    CCU2C neg_rom_addr0_r_n_0 (.A0(scuba_vlo), .A1(rom_addr0_r_inv), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(rom_addr0_r_n), .COUT(co0));

    defparam neg_rom_addr0_r_n_1.INJECT1_1 = "NO" ;
    defparam neg_rom_addr0_r_n_1.INJECT1_0 = "NO" ;
    defparam neg_rom_addr0_r_n_1.INIT1 =  16'h66AA ;
    defparam neg_rom_addr0_r_n_1.INIT0 =  16'h66AA ;
    CCU2C neg_rom_addr0_r_n_1 (.A0(rom_addr0_r_1_inv), .A1(rom_addr0_r_2_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co0), .S0(rom_addr0_r_n_1), 
        .S1(rom_addr0_r_n_2), .COUT(co1));

    defparam neg_rom_addr0_r_n_2.INJECT1_1 = "NO" ;
    defparam neg_rom_addr0_r_n_2.INJECT1_0 = "NO" ;
    defparam neg_rom_addr0_r_n_2.INIT1 =  16'h66AA ;
    defparam neg_rom_addr0_r_n_2.INIT0 =  16'h66AA ;
    CCU2C neg_rom_addr0_r_n_2 (.A0(rom_addr0_r_3_inv), .A1(rom_addr0_r_4_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co1), .S0(rom_addr0_r_n_3), 
        .S1(rom_addr0_r_n_4), .COUT(co2));

    defparam neg_rom_addr0_r_n_3.INJECT1_1 = "NO" ;
    defparam neg_rom_addr0_r_n_3.INJECT1_0 = "NO" ;
    defparam neg_rom_addr0_r_n_3.INIT1 =  16'h66AA ;
    defparam neg_rom_addr0_r_n_3.INIT0 =  16'h66AA ;
    CCU2C neg_rom_addr0_r_n_3 (.A0(rom_addr0_r_5_inv), .A1(rom_addr0_r_6_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co2), .S0(rom_addr0_r_n_5), 
        .S1(rom_addr0_r_n_6), .COUT(co3));

    defparam neg_rom_addr0_r_n_4.INJECT1_1 = "NO" ;
    defparam neg_rom_addr0_r_n_4.INJECT1_0 = "NO" ;
    defparam neg_rom_addr0_r_n_4.INIT1 =  16'h66AA ;
    defparam neg_rom_addr0_r_n_4.INIT0 =  16'h66AA ;
    CCU2C neg_rom_addr0_r_n_4 (.A0(rom_addr0_r_7_inv), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3), .S0(rom_addr0_r_n_7), .S1(), .COUT());

    defparam triglut_1_0_15.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    ROM256X1A triglut_1_0_15 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_7_ffin));

    defparam triglut_1_0_14.initval = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE000000000000000000000 ;
    ROM256X1A triglut_1_0_14 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_6_ffin));

    defparam triglut_1_0_13.initval = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0000000000001FFFFFFFFFFE0000000000 ;
    ROM256X1A triglut_1_0_13 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_5_ffin));

    defparam triglut_1_0_12.initval = 256'hFFFFFFFFFFFFFFFFFFFFE000000003FFFFFFC000001FFFFFC00001FFFFF00000 ;
    ROM256X1A triglut_1_0_12 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_4_ffin));

    defparam triglut_1_0_11.initval = 256'hFFFFFFFFFFFFFFE000001FFFFC0003FFF8003FFE001FFC003FF001FF800FFC00 ;
    ROM256X1A triglut_1_0_11 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_3_ffin));

    defparam triglut_1_0_10.initval = 256'hFFFFFFFFFFE0001FFF001FF803FC03FC07F03F81F81F83F03E0FC1F07E0F83E0 ;
    ROM256X1A triglut_1_0_10 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_2_ffin));

    defparam triglut_1_0_9.initval = 256'hFFFFFFFF001FF01FC0FC1F07C3C3C3C3870E3C71C71C738E31CE31CE718C631C ;
    ROM256X1A triglut_1_0_9 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_1_ffin));

    defparam triglut_1_0_8.initval = 256'hFFFFFF00FC1E0F1E38E39CE63333333366C9B24924924B692D2D2D2D694B5AD2 ;
    ROM256X1A triglut_1_0_8 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_ffin));

    defparam triglut_1_0_7.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    ROM256X1A triglut_1_0_7 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_15_ffin));

    defparam triglut_1_0_6.initval = 256'h000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF ;
    ROM256X1A triglut_1_0_6 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_14_ffin));

    defparam triglut_1_0_5.initval = 256'h0000000000FFFFFFFFFFF00000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFF ;
    ROM256X1A triglut_1_0_5 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_13_ffin));

    defparam triglut_1_0_4.initval = 256'h00001FFFFF000007FFFFF0000007FFFFFF800000000FFFFFFFFFFFFFFFFFFFFF ;
    ROM256X1A triglut_1_0_4 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_12_ffin));

    defparam triglut_1_0_3.initval = 256'h007FE003FF001FF8007FF000FFF8003FFF80007FFFF000000FFFFFFFFFFFFFFF ;
    ROM256X1A triglut_1_0_3 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_11_ffin));

    defparam triglut_1_0_2.initval = 256'h0F83E0FC1F07E0F81F83F03F03F81FC07F807F803FF001FFF0000FFFFFFFFFFF ;
    ROM256X1A triglut_1_0_2 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_10_ffin));

    defparam triglut_1_0_1.initval = 256'h718C631CE718E718E39C71C71C78E1C387878787C1F07E07F01FF001FFFFFFFF ;
    ROM256X1A triglut_1_0_1 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_9_ffin));

    defparam triglut_1_0_0.initval = 256'h96B5A52D696969692DA49249249B26CD99999998CE738E38F1E0F07E01FFFFFF ;
    ROM256X1A triglut_1_0_0 (.AD7(rom_addr0_r_15), .AD6(rom_addr0_r_14), 
        .AD5(rom_addr0_r_13), .AD4(rom_addr0_r_12), .AD3(rom_addr0_r_11), 
        .AD2(rom_addr0_r_10), .AD1(rom_addr0_r_9), .AD0(rom_addr0_r_8), 
        .DO0(rom_dout_8_ffin));

    defparam neg_rom_dout_s_n_0.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_s_n_0.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_s_n_0.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_s_n_0.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_s_n_0 (.A0(scuba_vlo), .A1(rom_dout_inv), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(rom_dout_s_n), .COUT(co0_1));

    defparam neg_rom_dout_s_n_1.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_s_n_1.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_s_n_1.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_s_n_1.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_s_n_1 (.A0(rom_dout_1_inv), .A1(rom_dout_2_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co0_1), .S0(rom_dout_s_n_1), 
        .S1(rom_dout_s_n_2), .COUT(co1_1));

    defparam neg_rom_dout_s_n_2.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_s_n_2.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_s_n_2.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_s_n_2.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_s_n_2 (.A0(rom_dout_3_inv), .A1(rom_dout_4_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co1_1), .S0(rom_dout_s_n_3), 
        .S1(rom_dout_s_n_4), .COUT(co2_1));

    defparam neg_rom_dout_s_n_3.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_s_n_3.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_s_n_3.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_s_n_3.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_s_n_3 (.A0(rom_dout_5_inv), .A1(rom_dout_6_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co2_1), .S0(rom_dout_s_n_5), 
        .S1(rom_dout_s_n_6), .COUT(co3_1));

    defparam neg_rom_dout_s_n_4.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_s_n_4.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_s_n_4.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_s_n_4.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_s_n_4 (.A0(rom_dout_7_inv), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_1), .S0(rom_dout_s_n_7), .S1(), .COUT());

    defparam neg_rom_dout_c_n_0.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_c_n_0.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_c_n_0.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_c_n_0.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_c_n_0 (.A0(scuba_vlo), .A1(rom_dout_8_inv), .B0(scuba_vlo), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(rom_dout_c_n), .COUT(co0_2));

    defparam neg_rom_dout_c_n_1.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_c_n_1.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_c_n_1.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_c_n_1.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_c_n_1 (.A0(rom_dout_9_inv), .A1(rom_dout_10_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co0_2), .S0(rom_dout_c_n_1), 
        .S1(rom_dout_c_n_2), .COUT(co1_2));

    defparam neg_rom_dout_c_n_2.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_c_n_2.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_c_n_2.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_c_n_2.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_c_n_2 (.A0(rom_dout_11_inv), .A1(rom_dout_12_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co1_2), .S0(rom_dout_c_n_3), 
        .S1(rom_dout_c_n_4), .COUT(co2_2));

    defparam neg_rom_dout_c_n_3.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_c_n_3.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_c_n_3.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_c_n_3.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_c_n_3 (.A0(rom_dout_13_inv), .A1(rom_dout_14_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co2_2), .S0(rom_dout_c_n_5), 
        .S1(rom_dout_c_n_6), .COUT(co3_2));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam neg_rom_dout_c_n_4.INJECT1_1 = "NO" ;
    defparam neg_rom_dout_c_n_4.INJECT1_0 = "NO" ;
    defparam neg_rom_dout_c_n_4.INIT1 =  16'h66AA ;
    defparam neg_rom_dout_c_n_4.INIT0 =  16'h66AA ;
    CCU2C neg_rom_dout_c_n_4 (.A0(rom_dout_15_inv), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co3_2), .S0(rom_dout_c_n_7), .S1(), .COUT());



    // exemplar begin
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
