/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 4.9 */
/* C:\lscc\diamond\3.14\ispfpga\bin\nt64\scuba.exe -w -n mult_m -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00g -type dspmult -simple_portname -pfu_mult -widtha 10 -widthb 4 -widthp 14 -signed -PL_stages 1 -input_reg -output_reg -clk0 -ce0 -rst0 -fdc C:/Users/SNA/Documents/FPGA_code/lattice_sdr_code/multiplier/mult_m/mult_m.fdc  */
/* Thu Jan 08 03:04:20 2026 */


`timescale 1 ns / 1 ps
module mult_m (Clock, ClkEn, Aclr, DataA, DataB, Result)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClkEn;
    input wire Aclr;
    input wire [9:0] DataA;
    input wire [3:0] DataB;
    output wire [13:0] Result;

    wire rego_o_0;
    wire rego_o_1;
    wire f_mult_m_0_pp_0_0;
    wire mult_m_0_pp_0_0;
    wire f_mult_m_0_pp_0_1;
    wire mult_m_0_pp_1_2;
    wire mult_m_0_pp_0_11;
    wire mult_m_0_pp_1_13;
    wire rego_o_2;
    wire f_mult_m_0_pp_1_2;
    wire f_mult_m_0_pp_0_2;
    wire rego_o_3;
    wire rego_o_4;
    wire f_mult_m_0_pp_1_4;
    wire f_mult_m_0_pp_1_3;
    wire f_mult_m_0_pp_0_4;
    wire f_mult_m_0_pp_0_3;
    wire co_t_mult_m_0_0_1;
    wire rego_o_5;
    wire rego_o_6;
    wire f_mult_m_0_pp_1_6;
    wire f_mult_m_0_pp_1_5;
    wire f_mult_m_0_pp_0_6;
    wire f_mult_m_0_pp_0_5;
    wire co_t_mult_m_0_0_2;
    wire rego_o_7;
    wire rego_o_8;
    wire f_mult_m_0_pp_1_8;
    wire f_mult_m_0_pp_1_7;
    wire f_mult_m_0_pp_0_8;
    wire f_mult_m_0_pp_0_7;
    wire co_t_mult_m_0_0_3;
    wire rego_o_9;
    wire rego_o_10;
    wire f_mult_m_0_pp_1_10;
    wire f_mult_m_0_pp_1_9;
    wire f_mult_m_0_pp_0_10;
    wire f_mult_m_0_pp_0_9;
    wire co_t_mult_m_0_0_4;
    wire rego_o_11;
    wire rego_o_12;
    wire f_mult_m_0_pp_1_12;
    wire f_mult_m_0_pp_1_11;
    wire f_mult_m_0_pp_0_11;
    wire co_t_mult_m_0_0_5;
    wire rego_o_13;
    wire co_t_mult_m_0_0_7;
    wire f_mult_m_0_pp_1_13;
    wire co_t_mult_m_0_0_6;
    wire mult_m_0_pp_0_2;
    wire mult_m_0_pp_0_1;
    wire mult_m_0_cin_lr_0;
    wire rega_a_0;
    wire mult_m_0_pp_0_4;
    wire mult_m_0_pp_0_3;
    wire mco;
    wire mult_m_0_pp_0_6;
    wire mult_m_0_pp_0_5;
    wire mco_1;
    wire mult_m_0_pp_0_8;
    wire mult_m_0_pp_0_7;
    wire mco_2;
    wire mfco;
    wire mult_m_0_pp_0_10;
    wire mult_m_0_pp_0_9;
    wire mco_3;
    wire regb_b_0;
    wire regb_b_1;
    wire mult_m_0_mult_0_4_n3;
    wire mult_m_0_mult_0_4_n1;
    wire mult_m_0_pp_1_4;
    wire mult_m_0_pp_1_3;
    wire mult_m_0_cin_lr;
    wire rega_a_2;
    wire mult_m_0_mult_2_0_n1;
    wire rega_a_1;
    wire mult_m_0_mult_2_0_n0;
    wire mult_m_0_pp_1_6;
    wire mult_m_0_pp_1_5;
    wire mco_4;
    wire rega_a_4;
    wire mult_m_0_mult_2_1_n1;
    wire rega_a_3;
    wire mult_m_0_mult_2_1_n0;
    wire mult_m_0_pp_1_8;
    wire mult_m_0_pp_1_7;
    wire mco_5;
    wire rega_a_6;
    wire mult_m_0_mult_2_2_n1;
    wire rega_a_5;
    wire mult_m_0_mult_2_2_n0;
    wire mult_m_0_pp_1_10;
    wire mult_m_0_pp_1_9;
    wire mco_6;
    wire rega_a_8;
    wire mult_m_0_mult_2_3_n1;
    wire rega_a_7;
    wire mult_m_0_mult_2_3_n0;
    wire mfco_1;
    wire mult_m_0_pp_1_12;
    wire mult_m_0_pp_1_11;
    wire mco_7;
    wire regb_b_2;
    wire regb_b_3;
    wire scuba_vhi;
    wire scuba_vlo;
    wire rega_a_9;
    wire mult_m_0_mult_2_4_n2;
    wire mult_m_0_mult_2_4_n0;

    AND2 AND2_t13 (.A(rega_a_0), .B(regb_b_0), .Z(mult_m_0_pp_0_0));

    ND2 ND2_t12 (.A(rega_a_9), .B(regb_b_0), .Z(mult_m_0_mult_0_4_n3));

    ND2 ND2_t11 (.A(rega_a_9), .B(regb_b_1), .Z(mult_m_0_mult_0_4_n1));

    AND2 AND2_t10 (.A(rega_a_0), .B(regb_b_2), .Z(mult_m_0_pp_1_2));

    ND2 ND2_t9 (.A(rega_a_1), .B(regb_b_3), .Z(mult_m_0_mult_2_0_n1));

    ND2 ND2_t8 (.A(rega_a_0), .B(regb_b_3), .Z(mult_m_0_mult_2_0_n0));

    ND2 ND2_t7 (.A(rega_a_3), .B(regb_b_3), .Z(mult_m_0_mult_2_1_n1));

    ND2 ND2_t6 (.A(rega_a_2), .B(regb_b_3), .Z(mult_m_0_mult_2_1_n0));

    ND2 ND2_t5 (.A(rega_a_5), .B(regb_b_3), .Z(mult_m_0_mult_2_2_n1));

    ND2 ND2_t4 (.A(rega_a_4), .B(regb_b_3), .Z(mult_m_0_mult_2_2_n0));

    ND2 ND2_t3 (.A(rega_a_7), .B(regb_b_3), .Z(mult_m_0_mult_2_3_n1));

    ND2 ND2_t2 (.A(rega_a_6), .B(regb_b_3), .Z(mult_m_0_mult_2_3_n0));

    ND2 ND2_t1 (.A(rega_a_9), .B(regb_b_2), .Z(mult_m_0_mult_2_4_n2));

    ND2 ND2_t0 (.A(rega_a_8), .B(regb_b_3), .Z(mult_m_0_mult_2_4_n0));

    FD1P3DX FF_51 (.D(DataA[0]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_50 (.D(DataA[1]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_49 (.D(DataA[2]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_48 (.D(DataA[3]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_47 (.D(DataA[4]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_46 (.D(DataA[5]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_45 (.D(DataA[6]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_44 (.D(DataA[7]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_43 (.D(DataA[8]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_42 (.D(DataA[9]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_41 (.D(DataB[0]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_40 (.D(DataB[1]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_39 (.D(DataB[2]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_38 (.D(DataB[3]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_37 (.D(rego_o_0), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_36 (.D(rego_o_1), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_35 (.D(rego_o_2), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_34 (.D(rego_o_3), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_33 (.D(rego_o_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_32 (.D(rego_o_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_31 (.D(rego_o_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_30 (.D(rego_o_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_29 (.D(rego_o_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(rego_o_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[9]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(rego_o_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[10]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(rego_o_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[11]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(rego_o_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[12]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(rego_o_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[13]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(mult_m_0_pp_0_0), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_0_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(mult_m_0_pp_0_1), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_0_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(mult_m_0_pp_0_2), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_0_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(mult_m_0_pp_0_3), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_0_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(mult_m_0_pp_0_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_0_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(mult_m_0_pp_0_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_0_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(mult_m_0_pp_0_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_0_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(mult_m_0_pp_0_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_0_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(mult_m_0_pp_0_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_0_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(mult_m_0_pp_0_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_0_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(mult_m_0_pp_0_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_0_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(mult_m_0_pp_0_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_0_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(mult_m_0_pp_1_2), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_1_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(mult_m_0_pp_1_3), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_1_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(mult_m_0_pp_1_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_1_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(mult_m_0_pp_1_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_1_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(mult_m_0_pp_1_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_1_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(mult_m_0_pp_1_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_1_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(mult_m_0_pp_1_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_1_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(mult_m_0_pp_1_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_1_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(mult_m_0_pp_1_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_1_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(mult_m_0_pp_1_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_1_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(mult_m_0_pp_1_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_1_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(mult_m_0_pp_1_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_mult_m_0_pp_1_13))
             /* synthesis GSR="ENABLED" */;

    defparam mult_m_0_cin_lr_add_0.INJECT1_1 = "NO" ;
    defparam mult_m_0_cin_lr_add_0.INJECT1_0 = "NO" ;
    defparam mult_m_0_cin_lr_add_0.INIT1 =  16'h0000 ;
    defparam mult_m_0_cin_lr_add_0.INIT0 =  16'h0000 ;
    CCU2C mult_m_0_cin_lr_add_0 (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(mult_m_0_cin_lr_0));

    defparam mult_m_0_Cadd_0_5.INJECT1_1 = "NO" ;
    defparam mult_m_0_Cadd_0_5.INJECT1_0 = "NO" ;
    defparam mult_m_0_Cadd_0_5.INIT1 =  16'h66AA ;
    defparam mult_m_0_Cadd_0_5.INIT0 =  16'h66AA ;
    CCU2C mult_m_0_Cadd_0_5 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(mfco), .S0(mult_m_0_pp_0_11), .S1(), .COUT());

    defparam mult_m_0_cin_lr_add.INJECT1_1 = "NO" ;
    defparam mult_m_0_cin_lr_add.INJECT1_0 = "NO" ;
    defparam mult_m_0_cin_lr_add.INIT1 =  16'h66AA ;
    defparam mult_m_0_cin_lr_add.INIT0 =  16'h66AA ;
    CCU2C mult_m_0_cin_lr_add (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(mult_m_0_cin_lr));

    defparam mult_m_0_Cadd_2_5.INJECT1_1 = "NO" ;
    defparam mult_m_0_Cadd_2_5.INJECT1_0 = "NO" ;
    defparam mult_m_0_Cadd_2_5.INIT1 =  16'h66AA ;
    defparam mult_m_0_Cadd_2_5.INIT0 =  16'h66AA ;
    CCU2C mult_m_0_Cadd_2_5 (.A0(scuba_vhi), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(mfco_1), .S0(mult_m_0_pp_1_13), .S1(), .COUT());

    defparam Cadd_t_mult_m_0_0_1.INJECT1_1 = "NO" ;
    defparam Cadd_t_mult_m_0_0_1.INJECT1_0 = "NO" ;
    defparam Cadd_t_mult_m_0_0_1.INIT1 =  16'h66AA ;
    defparam Cadd_t_mult_m_0_0_1.INIT0 =  16'h66AA ;
    CCU2C Cadd_t_mult_m_0_0_1 (.A0(scuba_vlo), .A1(f_mult_m_0_pp_0_2), .B0(scuba_vlo), 
        .B1(f_mult_m_0_pp_1_2), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(rego_o_2), .COUT(co_t_mult_m_0_0_1));

    defparam t_mult_m_0_add_0_2.INJECT1_1 = "NO" ;
    defparam t_mult_m_0_add_0_2.INJECT1_0 = "NO" ;
    defparam t_mult_m_0_add_0_2.INIT1 =  16'h66AA ;
    defparam t_mult_m_0_add_0_2.INIT0 =  16'h66AA ;
    CCU2C t_mult_m_0_add_0_2 (.A0(f_mult_m_0_pp_0_3), .A1(f_mult_m_0_pp_0_4), 
        .B0(f_mult_m_0_pp_1_3), .B1(f_mult_m_0_pp_1_4), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_t_mult_m_0_0_1), 
        .S0(rego_o_3), .S1(rego_o_4), .COUT(co_t_mult_m_0_0_2));

    defparam t_mult_m_0_add_0_3.INJECT1_1 = "NO" ;
    defparam t_mult_m_0_add_0_3.INJECT1_0 = "NO" ;
    defparam t_mult_m_0_add_0_3.INIT1 =  16'h66AA ;
    defparam t_mult_m_0_add_0_3.INIT0 =  16'h66AA ;
    CCU2C t_mult_m_0_add_0_3 (.A0(f_mult_m_0_pp_0_5), .A1(f_mult_m_0_pp_0_6), 
        .B0(f_mult_m_0_pp_1_5), .B1(f_mult_m_0_pp_1_6), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_t_mult_m_0_0_2), 
        .S0(rego_o_5), .S1(rego_o_6), .COUT(co_t_mult_m_0_0_3));

    defparam t_mult_m_0_add_0_4.INJECT1_1 = "NO" ;
    defparam t_mult_m_0_add_0_4.INJECT1_0 = "NO" ;
    defparam t_mult_m_0_add_0_4.INIT1 =  16'h66AA ;
    defparam t_mult_m_0_add_0_4.INIT0 =  16'h66AA ;
    CCU2C t_mult_m_0_add_0_4 (.A0(f_mult_m_0_pp_0_7), .A1(f_mult_m_0_pp_0_8), 
        .B0(f_mult_m_0_pp_1_7), .B1(f_mult_m_0_pp_1_8), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_t_mult_m_0_0_3), 
        .S0(rego_o_7), .S1(rego_o_8), .COUT(co_t_mult_m_0_0_4));

    defparam t_mult_m_0_add_0_5.INJECT1_1 = "NO" ;
    defparam t_mult_m_0_add_0_5.INJECT1_0 = "NO" ;
    defparam t_mult_m_0_add_0_5.INIT1 =  16'h66AA ;
    defparam t_mult_m_0_add_0_5.INIT0 =  16'h66AA ;
    CCU2C t_mult_m_0_add_0_5 (.A0(f_mult_m_0_pp_0_9), .A1(f_mult_m_0_pp_0_10), 
        .B0(f_mult_m_0_pp_1_9), .B1(f_mult_m_0_pp_1_10), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_t_mult_m_0_0_4), 
        .S0(rego_o_9), .S1(rego_o_10), .COUT(co_t_mult_m_0_0_5));

    defparam t_mult_m_0_add_0_6.INJECT1_1 = "NO" ;
    defparam t_mult_m_0_add_0_6.INJECT1_0 = "NO" ;
    defparam t_mult_m_0_add_0_6.INIT1 =  16'h66AA ;
    defparam t_mult_m_0_add_0_6.INIT0 =  16'h66AA ;
    CCU2C t_mult_m_0_add_0_6 (.A0(f_mult_m_0_pp_0_11), .A1(scuba_vlo), .B0(f_mult_m_0_pp_1_11), 
        .B1(f_mult_m_0_pp_1_12), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co_t_mult_m_0_0_5), .S0(rego_o_11), .S1(rego_o_12), 
        .COUT(co_t_mult_m_0_0_6));

    defparam t_mult_m_0_add_0_7.INJECT1_1 = "NO" ;
    defparam t_mult_m_0_add_0_7.INJECT1_0 = "NO" ;
    defparam t_mult_m_0_add_0_7.INIT1 =  16'h66AA ;
    defparam t_mult_m_0_add_0_7.INIT0 =  16'h66AA ;
    CCU2C t_mult_m_0_add_0_7 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(f_mult_m_0_pp_1_13), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co_t_mult_m_0_0_6), .S0(rego_o_13), .S1(), 
        .COUT(co_t_mult_m_0_0_7));

    defparam mult_m_0_mult_0_0.INJECT1_1 = "NO" ;
    defparam mult_m_0_mult_0_0.INJECT1_0 = "NO" ;
    defparam mult_m_0_mult_0_0.INIT1 =  16'h7888 ;
    defparam mult_m_0_mult_0_0.INIT0 =  16'h7888 ;
    CCU2C mult_m_0_mult_0_0 (.A0(rega_a_0), .A1(rega_a_1), .B0(regb_b_1), 
        .B1(regb_b_1), .C0(rega_a_1), .C1(rega_a_2), .D0(regb_b_0), .D1(regb_b_0), 
        .CIN(mult_m_0_cin_lr_0), .S0(mult_m_0_pp_0_1), .S1(mult_m_0_pp_0_2), 
        .COUT(mco));

    defparam mult_m_0_mult_0_1.INJECT1_1 = "NO" ;
    defparam mult_m_0_mult_0_1.INJECT1_0 = "NO" ;
    defparam mult_m_0_mult_0_1.INIT1 =  16'h7888 ;
    defparam mult_m_0_mult_0_1.INIT0 =  16'h7888 ;
    CCU2C mult_m_0_mult_0_1 (.A0(rega_a_2), .A1(rega_a_3), .B0(regb_b_1), 
        .B1(regb_b_1), .C0(rega_a_3), .C1(rega_a_4), .D0(regb_b_0), .D1(regb_b_0), 
        .CIN(mco), .S0(mult_m_0_pp_0_3), .S1(mult_m_0_pp_0_4), .COUT(mco_1));

    defparam mult_m_0_mult_0_2.INJECT1_1 = "NO" ;
    defparam mult_m_0_mult_0_2.INJECT1_0 = "NO" ;
    defparam mult_m_0_mult_0_2.INIT1 =  16'h7888 ;
    defparam mult_m_0_mult_0_2.INIT0 =  16'h7888 ;
    CCU2C mult_m_0_mult_0_2 (.A0(rega_a_4), .A1(rega_a_5), .B0(regb_b_1), 
        .B1(regb_b_1), .C0(rega_a_5), .C1(rega_a_6), .D0(regb_b_0), .D1(regb_b_0), 
        .CIN(mco_1), .S0(mult_m_0_pp_0_5), .S1(mult_m_0_pp_0_6), .COUT(mco_2));

    defparam mult_m_0_mult_0_3.INJECT1_1 = "NO" ;
    defparam mult_m_0_mult_0_3.INJECT1_0 = "NO" ;
    defparam mult_m_0_mult_0_3.INIT1 =  16'h7888 ;
    defparam mult_m_0_mult_0_3.INIT0 =  16'h7888 ;
    CCU2C mult_m_0_mult_0_3 (.A0(rega_a_6), .A1(rega_a_7), .B0(regb_b_1), 
        .B1(regb_b_1), .C0(rega_a_7), .C1(rega_a_8), .D0(regb_b_0), .D1(regb_b_0), 
        .CIN(mco_2), .S0(mult_m_0_pp_0_7), .S1(mult_m_0_pp_0_8), .COUT(mco_3));

    defparam mult_m_0_mult_0_4.INJECT1_1 = "NO" ;
    defparam mult_m_0_mult_0_4.INJECT1_0 = "NO" ;
    defparam mult_m_0_mult_0_4.INIT1 =  16'h7888 ;
    defparam mult_m_0_mult_0_4.INIT0 =  16'h7888 ;
    CCU2C mult_m_0_mult_0_4 (.A0(rega_a_8), .A1(mult_m_0_mult_0_4_n1), .B0(regb_b_1), 
        .B1(scuba_vhi), .C0(rega_a_9), .C1(mult_m_0_mult_0_4_n3), .D0(regb_b_0), 
        .D1(scuba_vhi), .CIN(mco_3), .S0(mult_m_0_pp_0_9), .S1(mult_m_0_pp_0_10), 
        .COUT(mfco));

    defparam mult_m_0_mult_2_0.INJECT1_1 = "NO" ;
    defparam mult_m_0_mult_2_0.INJECT1_0 = "NO" ;
    defparam mult_m_0_mult_2_0.INIT1 =  16'h7888 ;
    defparam mult_m_0_mult_2_0.INIT0 =  16'h7888 ;
    CCU2C mult_m_0_mult_2_0 (.A0(mult_m_0_mult_2_0_n0), .A1(mult_m_0_mult_2_0_n1), 
        .B0(scuba_vhi), .B1(scuba_vhi), .C0(rega_a_1), .C1(rega_a_2), .D0(regb_b_2), 
        .D1(regb_b_2), .CIN(mult_m_0_cin_lr), .S0(mult_m_0_pp_1_3), .S1(mult_m_0_pp_1_4), 
        .COUT(mco_4));

    defparam mult_m_0_mult_2_1.INJECT1_1 = "NO" ;
    defparam mult_m_0_mult_2_1.INJECT1_0 = "NO" ;
    defparam mult_m_0_mult_2_1.INIT1 =  16'h7888 ;
    defparam mult_m_0_mult_2_1.INIT0 =  16'h7888 ;
    CCU2C mult_m_0_mult_2_1 (.A0(mult_m_0_mult_2_1_n0), .A1(mult_m_0_mult_2_1_n1), 
        .B0(scuba_vhi), .B1(scuba_vhi), .C0(rega_a_3), .C1(rega_a_4), .D0(regb_b_2), 
        .D1(regb_b_2), .CIN(mco_4), .S0(mult_m_0_pp_1_5), .S1(mult_m_0_pp_1_6), 
        .COUT(mco_5));

    defparam mult_m_0_mult_2_2.INJECT1_1 = "NO" ;
    defparam mult_m_0_mult_2_2.INJECT1_0 = "NO" ;
    defparam mult_m_0_mult_2_2.INIT1 =  16'h7888 ;
    defparam mult_m_0_mult_2_2.INIT0 =  16'h7888 ;
    CCU2C mult_m_0_mult_2_2 (.A0(mult_m_0_mult_2_2_n0), .A1(mult_m_0_mult_2_2_n1), 
        .B0(scuba_vhi), .B1(scuba_vhi), .C0(rega_a_5), .C1(rega_a_6), .D0(regb_b_2), 
        .D1(regb_b_2), .CIN(mco_5), .S0(mult_m_0_pp_1_7), .S1(mult_m_0_pp_1_8), 
        .COUT(mco_6));

    defparam mult_m_0_mult_2_3.INJECT1_1 = "NO" ;
    defparam mult_m_0_mult_2_3.INJECT1_0 = "NO" ;
    defparam mult_m_0_mult_2_3.INIT1 =  16'h7888 ;
    defparam mult_m_0_mult_2_3.INIT0 =  16'h7888 ;
    CCU2C mult_m_0_mult_2_3 (.A0(mult_m_0_mult_2_3_n0), .A1(mult_m_0_mult_2_3_n1), 
        .B0(scuba_vhi), .B1(scuba_vhi), .C0(rega_a_7), .C1(rega_a_8), .D0(regb_b_2), 
        .D1(regb_b_2), .CIN(mco_6), .S0(mult_m_0_pp_1_9), .S1(mult_m_0_pp_1_10), 
        .COUT(mco_7));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam mult_m_0_mult_2_4.INJECT1_1 = "NO" ;
    defparam mult_m_0_mult_2_4.INJECT1_0 = "NO" ;
    defparam mult_m_0_mult_2_4.INIT1 =  16'h7888 ;
    defparam mult_m_0_mult_2_4.INIT0 =  16'h7888 ;
    CCU2C mult_m_0_mult_2_4 (.A0(mult_m_0_mult_2_4_n0), .A1(rega_a_9), .B0(scuba_vhi), 
        .B1(regb_b_3), .C0(mult_m_0_mult_2_4_n2), .C1(scuba_vlo), .D0(scuba_vhi), 
        .D1(regb_b_2), .CIN(mco_7), .S0(mult_m_0_pp_1_11), .S1(mult_m_0_pp_1_12), 
        .COUT(mfco_1));

    assign rego_o_0 = f_mult_m_0_pp_0_0;
    assign rego_o_1 = f_mult_m_0_pp_0_1;


    // exemplar begin
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
